# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."vert" = {
    image = "ghcr.io/vert-sh/vert:latest";
    ports = [
      "3080:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=vert"
      "--network-alias=vert"
      "--network=vert-sh_default"
    ];
  };
  systemd.services."podman-vert" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vert-sh_default.service"
    ];
    requires = [
      "podman-network-vert-sh_default.service"
    ];
    partOf = [
      "podman-compose-vert-sh-root.target"
    ];
    wantedBy = [
      "podman-compose-vert-sh-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-vert-sh_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f vert-sh_default";
    };
    script = ''
      podman network inspect vert-sh_default || podman network create vert-sh_default
    '';
    partOf = ["podman-compose-vert-sh-root.target"];
    wantedBy = ["podman-compose-vert-sh-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-vert-sh-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
