# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."resume-matcher" = {
    image = "ghcr.io/mrdgh2821/resume-matcher:latest";
    volumes = [
      "/etc/nixos/persist/nix/modules/container-services/resume-matcher/app/backend/data:/app/backend/data:rw"
    ];
    ports = [
      "3100:3000/tcp"
      "8000:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"curl\", \"-f\", \"http://localhost:8000/api/v1/health\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=10s"
      "--hostname=resume-matcher"
      "--network-alias=resume-matcher"
      "--network=resume-matcher_default"
    ];
  };
  systemd.services."podman-resume-matcher" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-resume-matcher_default.service"
    ];
    requires = [
      "podman-network-resume-matcher_default.service"
    ];
    partOf = [
      "podman-compose-resume-matcher-root.target"
    ];
    wantedBy = [
      "podman-compose-resume-matcher-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-resume-matcher_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f resume-matcher_default";
    };
    script = ''
      podman network inspect resume-matcher_default || podman network create resume-matcher_default
    '';
    partOf = ["podman-compose-resume-matcher-root.target"];
    wantedBy = ["podman-compose-resume-matcher-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-resume-matcher-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
