# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."hermes-workspace-hermes-workspace" = {
    image = "ghcr.io/outsourc-e/hermes-workspace:latest";
    ports = [
      "127.0.0.1:3100:3100/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=hermes-workspace"
      "--network=hermes-workspace_default"
    ];
  };
  systemd.services."podman-hermes-workspace-hermes-workspace" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-hermes-workspace_default.service"
    ];
    requires = [
      "podman-network-hermes-workspace_default.service"
    ];
    partOf = [
      "podman-compose-hermes-workspace-root.target"
    ];
    wantedBy = [
      "podman-compose-hermes-workspace-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-hermes-workspace_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f hermes-workspace_default";
    };
    script = ''
      podman network inspect hermes-workspace_default || podman network create hermes-workspace_default
    '';
    partOf = ["podman-compose-hermes-workspace-root.target"];
    wantedBy = ["podman-compose-hermes-workspace-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-hermes-workspace-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
