keys:
  - &bose_game_user age18mhd309clh6tm24nm68zu2jl5nslwre64ap7sucuquslhy94pcksdg793a
  - &server_home_lab age1t6v85ppu92lhfclws5e2wqng3v3a2yjmzyuaamv6tt0v3zsdxa9s3vxwu6

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *bose_game_user
          - *server_home_lab
