creation_rules:
  - key_groups:
      - age:
          - age18mhd309clh6tm24nm68zu2jl5nslwre64ap7sucuquslhy94pcksdg793a
          - age1t6v85ppu92lhfclws5e2wqng3v3a2yjmzyuaamv6tt0v3zsdxa9s3vxwu6
    path_regex: (.*/)?secrets/.*\.(yaml|json|env|ini)$
keys:
  - age18mhd309clh6tm24nm68zu2jl5nslwre64ap7sucuquslhy94pcksdg793a
  - age1t6v85ppu92lhfclws5e2wqng3v3a2yjmzyuaamv6tt0v3zsdxa9s3vxwu6
