[config]
"nix/hosts/home-lab/secrets/agecrypt/test.txt" = [
    "age18mhd309clh6tm24nm68zu2jl5nslwre64ap7sucuquslhy94pcksdg793a",
]
"./nix/hosts/home-lab/secrets/agecrypt/test.txt" = [
    "age18mhd309clh6tm24nm68zu2jl5nslwre64ap7sucuquslhy94pcksdg793a",
]
"nix/hosts/home-lab/secrets/agecrypt/secrets.nix" = [
    "age18mhd309clh6tm24nm68zu2jl5nslwre64ap7sucuquslhy94pcksdg793a",
]
"./nix/hosts/home-lab/secrets/agecrypt/secrets.nix" = [
    "age18mhd309clh6tm24nm68zu2jl5nslwre64ap7sucuquslhy94pcksdg793a",
]
