# Auto-generated by compose2nix.
{
  config,
  lib,
  pkgs,
  ...
}: {
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };
  systemd = {
    services = {
      "podman-omniroute-web" = {
        after = [
          "podman-volume-omniroute_omniroute.service"
        ];
        partOf = [
          "podman-compose-omniroute-root.target"
        ];
        requires = [
          "podman-volume-omniroute_omniroute.service"
        ];
        serviceConfig.Restart = lib.mkOverride 90 "always";
        wantedBy = [
          "podman-compose-omniroute-root.target"
        ];
      };
      # Volumes
      "podman-volume-omniroute_omniroute" = {
        partOf = ["podman-compose-omniroute-root.target"];
        path = [pkgs.podman];
        script = ''
          podman volume inspect omniroute_omniroute || podman volume create omniroute_omniroute
        '';
        serviceConfig = {
          RemainAfterExit = true;
          Type = "oneshot";
        };
        wantedBy = ["podman-compose-omniroute-root.target"];
      };
    };
    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-omniroute-root" = {
      unitConfig.Description = "Root target generated by compose2nix.";
      wantedBy = ["multi-user.target"];
    };
  };
  virtualisation = {
    oci-containers = {
      backend = "podman";
      # Containers
      containers."omniroute-web" = {
        extraOptions = [
          "--hostname=omniroute-web"
          "--network=host"
        ];
        image = "ghcr.io/diegosouzapw/omniroute:3.8.50-web";
        log-driver = "journald";
        ports = [
          "20128:20128/tcp"
          "20129:20129/tcp"
        ];
        volumes = [
          "omniroute_omniroute:/app/data:rw"
        ];
      };
    };
    # Runtime
    podman = {
      autoPrune.enable = true;
      dockerCompat = true;
      enable = true;
    };
  };
}
