# Auto-generated using compose2nix v0.3.3-pre.
{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."portnote-agent" = {
    image = "haedlessdev/portnote-agent:latest";
    log-driver = "journald";
    extraOptions = [
      "--hostname=portnote-agent"
      "--network-alias=agent"
      "--network=portnote_default"
    ];
  };
  systemd.services."docker-portnote-agent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-portnote_default.service"
    ];
    requires = [
      "docker-network-portnote_default.service"
    ];
    partOf = [
      "docker-compose-portnote-root.target"
    ];
    wantedBy = [
      "docker-compose-portnote-root.target"
    ];
  };
  virtualisation.oci-containers.containers."portnote-web" = {
    image = "haedlessdev/portnote:latest";
    ports = [
      "3050:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:172.17.0.1"
      "--hostname=portnote-web"
      "--network-alias=web"
      "--network=portnote_default"
    ];
  };
  systemd.services."docker-portnote-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-portnote_default.service"
    ];
    requires = [
      "docker-network-portnote_default.service"
    ];
    partOf = [
      "docker-compose-portnote-root.target"
    ];
    wantedBy = [
      "docker-compose-portnote-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-portnote_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f portnote_default";
    };
    script = ''
      docker network inspect portnote_default || docker network create portnote_default
    '';
    partOf = ["docker-compose-portnote-root.target"];
    wantedBy = ["docker-compose-portnote-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-portnote-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
