# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."omniroute-web" = {
    image = "ghcr.io/diegosouzapw/omniroute:3.8.31-web";
    volumes = [
      "omniroute_omniroute:/app/data:rw"
    ];
    ports = [
      "20128:20128/tcp"
      "20129:20129/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=omniroute-web"
      "--network=host"
    ];
  };
  systemd.services."podman-omniroute-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-volume-omniroute_omniroute.service"
    ];
    requires = [
      "podman-volume-omniroute_omniroute.service"
    ];
    partOf = [
      "podman-compose-omniroute-root.target"
    ];
    wantedBy = [
      "podman-compose-omniroute-root.target"
    ];
  };

  # Volumes
  systemd.services."podman-volume-omniroute_omniroute" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect omniroute_omniroute || podman volume create omniroute_omniroute
    '';
    partOf = ["podman-compose-omniroute-root.target"];
    wantedBy = ["podman-compose-omniroute-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-omniroute-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
