# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."hermes-webui" = {
    image = "ghcr.io/nesquena/hermes-webui:latest";
    volumes = [
      "/etc/nixos/persist/hermes-agent/.hermes:/home/hermeswebui/.hermes:rw"
      "/etc/nixos/persist/hermes-agent/current-package:/home/hermeswebui/.hermes/hermes-agent:ro"
      "/etc/nixos/persist/hermes-agent/workspace:/workspace:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=hermes-webui"
      "--network=host"
    ];
  };
  systemd.services."podman-hermes-webui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-hermes-webui-root.target"
    ];
    wantedBy = [
      "podman-compose-hermes-webui-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-hermes-webui-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
