---
trust:
  - https://github.com/MRDGH2821/copier-mr-minimal.git
  - gh:MRDGH2821/copier-mr-minimal
  - https://gitlab.com/axisnexa/an-repo-template.git
  - gl:axisnexa/an-repo-template
  - https://gitlab.com/AxisNexa/an-repo-template.git
  - gl:AxisNexa/an-repo-template
  - https://github.com/MRDGH2821/copier-mr-mise.git
  - gh:MRDGH2821/copier-mr-mise
