---
name: honcho-memory
services:
  api:
    # healthcheck:
    #   interval: 5s
    #   retries: 5
    #   start_period: 10s
    #   test:
    #     - CMD
    #     - /app/.venv/bin/python
    #     - -c
    #     - import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=2).read()
    #   timeout: 5s
    image: ghcr.io/plastic-labs/honcho:v3.0.10
    network_mode: host
    restart: unless-stopped
  deriver:
    depends_on:
      - api
    entrypoint:
      - /app/.venv/bin/python
      - -m
      - src.deriver
    image: ghcr.io/plastic-labs/honcho:v3.0.10
    network_mode: host
    restart: unless-stopped
  migrate:
    entrypoint:
      - /app/.venv/bin/alembic
      - upgrade
      - head
    image: ghcr.io/plastic-labs/honcho:v3.0.10
    network_mode: host
    restart: "no"
