# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."honcho-memory-api" = {
    image = "ghcr.io/plastic-labs/honcho:v3.0.11";
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-honcho-memory-api" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-honcho-memory-root.target"
    ];
    wantedBy = [
      "podman-compose-honcho-memory-root.target"
    ];
  };
  virtualisation.oci-containers.containers."honcho-memory-deriver" = {
    image = "ghcr.io/plastic-labs/honcho:v3.0.11";
    dependsOn = [
      "honcho-memory-api"
    ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"/app/.venv/bin/python\", \"-m\", \"src.deriver\"]"
      "--network=host"
    ];
  };
  systemd.services."podman-honcho-memory-deriver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-honcho-memory-root.target"
    ];
    wantedBy = [
      "podman-compose-honcho-memory-root.target"
    ];
  };
  virtualisation.oci-containers.containers."honcho-memory-migrate" = {
    image = "ghcr.io/plastic-labs/honcho:v3.0.11";
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"/app/.venv/bin/alembic\", \"upgrade\", \"head\"]"
      "--network=host"
    ];
  };
  systemd.services."podman-honcho-memory-migrate" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "podman-compose-honcho-memory-root.target"
    ];
    wantedBy = [
      "podman-compose-honcho-memory-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-honcho-memory-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
