# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."honcho-memory-api" = {
    image = "ghcr.io/plastic-labs/honcho:latest";
    ports = [
      "8000:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"/app/.venv/bin/python\", \"-c\", \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=2).read()\"]"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-start-period=10s"
      "--health-timeout=5s"
      "--network-alias=api"
      "--network=honcho-memory_default"
    ];
  };
  systemd.services."podman-honcho-memory-api" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-honcho-memory_default.service"
    ];
    requires = [
      "podman-network-honcho-memory_default.service"
    ];
    partOf = [
      "podman-compose-honcho-memory-root.target"
    ];
    wantedBy = [
      "podman-compose-honcho-memory-root.target"
    ];
  };
  virtualisation.oci-containers.containers."honcho-memory-deriver" = {
    image = "ghcr.io/plastic-labs/honcho:latest";
    dependsOn = [
      "honcho-memory-api"
    ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"/app/.venv/bin/python\", \"-m\", \"src.deriver\"]"
      "--network-alias=deriver"
      "--network=honcho-memory_default"
    ];
  };
  systemd.services."podman-honcho-memory-deriver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-honcho-memory_default.service"
    ];
    requires = [
      "podman-network-honcho-memory_default.service"
    ];
    partOf = [
      "podman-compose-honcho-memory-root.target"
    ];
    wantedBy = [
      "podman-compose-honcho-memory-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-honcho-memory_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f honcho-memory_default";
    };
    script = ''
      podman network inspect honcho-memory_default || podman network create honcho-memory_default
    '';
    partOf = ["podman-compose-honcho-memory-root.target"];
    wantedBy = ["podman-compose-honcho-memory-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-honcho-memory-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
