# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."bentopdf" = {
    image = "bentopdf/bentopdf:latest";
    ports = [
      "8090:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=bentopdf"
      "--network-alias=bentopdf"
      "--network=bentopdf_default"
    ];
  };
  systemd.services."docker-bentopdf" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bentopdf_default.service"
    ];
    requires = [
      "docker-network-bentopdf_default.service"
    ];
    partOf = [
      "docker-compose-bentopdf-root.target"
    ];
    wantedBy = [
      "docker-compose-bentopdf-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-bentopdf_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f bentopdf_default";
    };
    script = ''
      docker network inspect bentopdf_default || docker network create bentopdf_default
    '';
    partOf = ["docker-compose-bentopdf-root.target"];
    wantedBy = ["docker-compose-bentopdf-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-bentopdf-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
