# Auto-generated by compose2nix.
{
  config,
  lib,
  pkgs,
  ...
}: {
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };
  systemd = {
    services = {
      # Networks
      "podman-network-omni-tools_default" = {
        partOf = ["podman-compose-omni-tools-root.target"];
        path = [pkgs.podman];
        script = ''
          podman network inspect omni-tools_default || podman network create omni-tools_default
        '';
        serviceConfig = {
          ExecStop = "podman network rm -f omni-tools_default";
          RemainAfterExit = true;
          Type = "oneshot";
        };
        wantedBy = ["podman-compose-omni-tools-root.target"];
      };
      "podman-omni-tools" = {
        after = [
          "podman-network-omni-tools_default.service"
        ];
        partOf = [
          "podman-compose-omni-tools-root.target"
        ];
        requires = [
          "podman-network-omni-tools_default.service"
        ];
        serviceConfig.Restart = lib.mkOverride 90 "always";
        wantedBy = [
          "podman-compose-omni-tools-root.target"
        ];
      };
    };
    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-omni-tools-root" = {
      unitConfig.Description = "Root target generated by compose2nix.";
      wantedBy = ["multi-user.target"];
    };
  };
  virtualisation = {
    oci-containers = {
      backend = "podman";
      # Containers
      containers."omni-tools" = {
        extraOptions = [
          "--hostname=omni-tools"
          "--network-alias=omni-tools"
          "--network=omni-tools_default"
        ];
        image = "iib0011/omni-tools:0.6.0";
        log-driver = "journald";
        ports = [
          "3081:80/tcp"
        ];
      };
    };
    # Runtime
    podman = {
      autoPrune.enable = true;
      dockerCompat = true;
      enable = true;
    };
  };
}
