# Auto-generated by compose2nix.
{
  config,
  lib,
  ...
}: {
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };
  systemd = {
    services = {
      "podman-honcho-memory-api" = {
        partOf = [
          "podman-compose-honcho-memory-root.target"
        ];
        serviceConfig.Restart = lib.mkOverride 90 "always";
        wantedBy = [
          "podman-compose-honcho-memory-root.target"
        ];
      };
      "podman-honcho-memory-deriver" = {
        partOf = [
          "podman-compose-honcho-memory-root.target"
        ];
        serviceConfig.Restart = lib.mkOverride 90 "always";
        wantedBy = [
          "podman-compose-honcho-memory-root.target"
        ];
      };
      "podman-honcho-memory-migrate" = {
        partOf = [
          "podman-compose-honcho-memory-root.target"
        ];
        serviceConfig.Restart = lib.mkOverride 90 "no";
        wantedBy = [
          "podman-compose-honcho-memory-root.target"
        ];
      };
    };
    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    targets."podman-compose-honcho-memory-root" = {
      unitConfig.Description = "Root target generated by compose2nix.";
      wantedBy = ["multi-user.target"];
    };
  };
  virtualisation = {
    oci-containers = {
      backend = "podman";
      containers = {
        # Containers
        "honcho-memory-api" = {
          extraOptions = [
            "--network=host"
          ];
          image = "ghcr.io/plastic-labs/honcho:v3.0.12";
          log-driver = "journald";
        };
        "honcho-memory-deriver" = {
          dependsOn = [
            "honcho-memory-api"
          ];
          extraOptions = [
            "--entrypoint=[\"/app/.venv/bin/python\", \"-m\", \"src.deriver\"]"
            "--network=host"
          ];
          image = "ghcr.io/plastic-labs/honcho:v3.0.12";
          log-driver = "journald";
        };
        "honcho-memory-migrate" = {
          extraOptions = [
            "--entrypoint=[\"/app/.venv/bin/alembic\", \"upgrade\", \"head\"]"
            "--network=host"
          ];
          image = "ghcr.io/plastic-labs/honcho:v3.0.12";
          log-driver = "journald";
        };
      };
    };
    # Runtime
    podman = {
      autoPrune.enable = true;
      dockerCompat = true;
      enable = true;
    };
  };
}
