# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."docker-socket-proxy" = {
    image = "ghcr.io/tecnativa/docker-socket-proxy:latest";
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "127.0.0.1:2375:2375/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=docker-socket-proxy"
      "--network-alias=docker-socket-proxy"
      "--network=docker-socket-proxy_default"
    ];
  };
  systemd.services."docker-docker-socket-proxy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-docker-socket-proxy_default.service"
    ];
    requires = [
      "docker-network-docker-socket-proxy_default.service"
    ];
    partOf = [
      "docker-compose-docker-socket-proxy-root.target"
    ];
    wantedBy = [
      "docker-compose-docker-socket-proxy-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-docker-socket-proxy_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f docker-socket-proxy_default";
    };
    script = ''
      docker network inspect docker-socket-proxy_default || docker network create docker-socket-proxy_default
    '';
    partOf = ["docker-compose-docker-socket-proxy-root.target"];
    wantedBy = ["docker-compose-docker-socket-proxy-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-docker-socket-proxy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
