# Auto-generated using compose2nix v0.3.3-pre.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."bewcloud-website" = {
    image = "ghcr.io/bewcloud/bewcloud:v2.7.1";
    volumes = [
      "/etc/nixos/persist/bewcloud/bewcloud.config.ts:/app/bewcloud.config.ts:rw"
      "/etc/nixos/persist/bewcloud/data-files:/app/data-files:rw"
    ];
    ports = [
      "8000:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=website"
      "--network=bewcloud_default"
    ];
    environmentFiles = [
      config.sops.secrets.bewcloud.path
    ];
  };
  systemd.services."docker-bewcloud-website" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bewcloud_default.service"
    ];
    requires = [
      "docker-network-bewcloud_default.service"
    ];
    partOf = [
      "docker-compose-bewcloud-root.target"
    ];
    wantedBy = [
      "docker-compose-bewcloud-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-bewcloud_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f bewcloud_default";
    };
    script = ''
      docker network inspect bewcloud_default || docker network create bewcloud_default
    '';
    partOf = ["docker-compose-bewcloud-root.target"];
    wantedBy = ["docker-compose-bewcloud-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-bewcloud-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
